name: Build and Publish to JFrog Artifactory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Set up JFrog CLI
      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        with:
          version: '2.73.2' # Updated version
          server-id: 'artifactory-server'
          url: ${{ secrets.JFROG_URL }}
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run build
      - name: Build the project
        run: npm run build

      # Step 6: Configure JFrog CLI (explicitly)
      - name: Configure JFrog CLI
        run: |
          jf c add artifactory-server \
            --url=${{ secrets.JFROG_URL }} \
            --user=${{ secrets.JFROG_USERNAME }} \
            --password=${{ secrets.JFROG_PASSWORD }} \
            --interactive=false

      # Step 7: Upload build output to Artifactory
      - name: Upload build output to Artifactory
        run: |
          jf rt u "dist/**/*" "cli-npm/test-red/" \
            --build-name=my-npm-build \
            --build-number=${{ github.run_number }} \
            --server-id=artifactory-server

      # Step 8: Publish Build Info
      - name: Publish Build Info
        run: |
          jf rt build-publish my-npm-build ${{ github.run_number }}
